### ISSUE TITLE
Beschreibung vervollständigen

### ISSUE THREAD

**Issue by Olli** [vrpayment/contao-intranet-bundle#1]
Hi,
bitte schreib mal in die Beschreibung rein, was diese nicen Funktionen denn sind. 
Danke :)

**Comment by SgnAtWork** [comment]
Hi,

Momentan ist das eine sehr einfache bestellfunktion für einen Mittagstisch . Kommt möglicherweise noch mehr dazu , im Moment ist es aber eben nur ein Modul was ne Mail verschickt und einen csv Export macht ;)

Viele Grüße
Holger Neuner

Von meinem iPhone gesendet

Am 30.10.2019 um 13:04 schrieb Olli <notifications@github.com<mailto:notifications@github.com>>:


Hi,
bitte schreib mal in die Beschreibung rein, was diese nicen Funktionen denn sind.
Danke :)

**Comment by Olli** [comment]
Alles klar - danke
